name: aws-deploy
run-name: Deploy to AWS
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: 'eu-central-1'

jobs:
  deploy-dev:
    environment: staging
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Generate OpenAPI
        run: npm run openapi

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'eu-central-1'

      - name: Bootstrap
        run: npm run cdk bootstrap
        env:
          ENV_NAME: dev
          AUDIENCE: ${{ secrets.AUDIENCE }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
          ALLOWED_UPLOAD_ORIGINS: '*'

      - name: Diff stack
        run: npm run cdk diff
        env:
          ENV_NAME: dev
          AUDIENCE: ${{ secrets.AUDIENCE }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
          ALLOWED_UPLOAD_ORIGINS: '*'

      - name: Deploy stack
        run: npx cdk deploy --all --require-approval never
        env:
          ENV_NAME: dev
          AUDIENCE: ${{ secrets.AUDIENCE }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
          ALLOWED_UPLOAD_ORIGINS: '*'

  deploy-prod:
    name: Deploy to prod
    environment: prod
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Generate OpenAPI
        run: npm run generate:openapi

      - name: Build
        run: npm run build

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'eu-central-1'

      - name: Bootstrap
        run: npm run cdk bootstrap
        env:
          ENV_NAME: prod
          AUDIENCE: ${{ secrets.AUDIENCE }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          JWKS_URI: ${{ secrets.JWKS_URI }}

      - name: Diff stack
        run: npm run cdk diff
        env:
          ENV_NAME: prod
          AUDIENCE: ${{ secrets.AUDIENCE }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          JWKS_URI: ${{ secrets.JWKS_URI }}

      - name: Deploy stack
        run: npx cdk deploy --all --require-approval never
        env:
          ENV_NAME: prod
          AUDIENCE: ${{ secrets.AUDIENCE }}
          TOKEN_ISSUER: ${{ secrets.TOKEN_ISSUER }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
